### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by hl8086** [benedekrozemberczki/GraRep#1]
you have a nice job, but i have some questions about the method of   ‘ _create_target_matrix ’：
1. scores = np.log(self.A_hat.data) - math.log(self.A.shape[0])   # self.A_hat.data needs to scaling ?
2.  scores = scores[scores < 0]  # you keep the negative entries, but the paper assigns negative entries of Xk to zero ?

**Comment by benedekrozemberczki** [comment]
Did you read the GraRep paper?
